// Code generated by Kitex v0.0.5. DO NOT EDIT.

package servicenamedaytimeinthriftfile

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"module_name_daytime/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Daytime(ctx context.Context, req *api.DaytimeRequest, callOptions ...callopt.Option) (r *api.DaytimeResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kServiceNameDaytimeInThriftFileClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kServiceNameDaytimeInThriftFileClient struct {
	*kClient
}

func (p *kServiceNameDaytimeInThriftFileClient) Daytime(ctx context.Context, req *api.DaytimeRequest, callOptions ...callopt.Option) (r *api.DaytimeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Daytime(ctx, req)
}
